### ISSUE TITLE
the documentation on gitbook.com is not latest

### ISSUE THREAD

**Issue by litt1e-p** [beeth0ven/RxSwift-Chinese-Documentation#10]
@beeth0ven thanks for your great documentation, I found it on [gitbook.com](https://gitbook.com), but it is the earlier version there which rendering with some error with ePub format, will it update with latest version?

**Comment by beeth0ven** [comment]
Hi @litt1e-p thanks for your kind words. 

Because there are many restrictions on [gitbook.com](https://gitbook.com/). e.g We can't fold catalog. 

Finally I decided to use [Github Pages](https://pages.github.com).

Providing eBooks is a great advice. So I add a [RxSwiftChineseDocumentation.epub](https://github.com/beeth0ven/RxSwift-Chinese-Documentation/releases/download/0.2.0/RxSwiftChineseDocumentation.epub) file to latest release (0.2.0).

have fun.

**Comment by litt1e-p** [comment]
thx
